### ISSUE TITLE
Why is TraceProcessor a singleton?

### ISSUE THREAD

**Issue by jcp19** [fntneves/falcon#40]
At times, I need to have two separate instances of `TraceProcessor` in order to handle two different traces in the same program. However, this class is implemented as a singleton. Is there any particular reason for this class to be be implemented like this?

At first sight, it looks like the only change required to make this class 'not a singleton' would be to change the access modifier on the only available constrcutor.

**Comment by fntneves** [comment]
Hello @jcp19,

There is no particular reason for making TraceProcessor a singleton.
We can change that and delegate such decision to libraries/tools using it.

Do you want to open a PR?

**Comment by jcp19** [comment]
I will as soon as I can :)
